language: objective-c
env:
  matrix:
    - FORMULA_VERSION=
    - FORMULA_VERSION=--HEAD
rvm: system
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/dbcli
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/dbcli/homebrew-tap
script:
  - brew install pgcli $FORMULA_VERSION --verbose
  - brew audit pgcli --strict
  - brew test pgcli
  - pgcli --help
matrix:
  fast_finish: true
